name: Matrix bot

on:
  push:
    branches:
      - master
  pull_request_target:
    types: [opened, edited, reopened, closed]
  issues:
    types: [opened, edited, milestoned, closed]

jobs:
  matrix_action_job:
    runs-on: ubuntu-latest
    name: Send Message to Matrix Room
    env:
      REPO: "https://github.com/aurelienpierreeng/ansel"
      ROOM: "!khBjOtEnQNuCYlWScJ:matrix.org"
    steps:

    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 1

    - name: Install dependencies
      run: |
        python -m pip install simplematrixbotlib

    - name: Dispatch message - new commit
      if: github.event_name == 'push'
      run: |
        GIT_HASH=$(git rev-parse HEAD)
        MESSAGE="Commit [$(git rev-parse --short HEAD)](${{ env.REPO }}/commit/${GIT_HASH}): $(git show -s --format=%s)"
        python .ci/matrix.py \
        -m "$MESSAGE" \
        -s ${{ secrets.MATRIX_SERVER }} \
        -u ${{ secrets.MATRIX_USER }} \
        -t ${{ secrets.MATRIX_ACCESS }} \
        -r ${{ env.ROOM }}

    - name: Dispatch message - new issue
      if: ${{ github.event_name == 'issues' && github.event.action == 'opened' }}
      run: |
        MESSAGE="New issue [${{ github.event.issue.number }}](${{ github.event.issue.html_url }}) (_${{ github.event.issue.title }}_) created"
        python .ci/matrix.py \
        -m "$MESSAGE" \
        -s ${{ secrets.MATRIX_SERVER }} \
        -u ${{ secrets.MATRIX_USER }} \
        -t ${{ secrets.MATRIX_ACCESS }} \
        -r ${{ env.ROOM }}

    - name: Dispatch message - issue edited
      if: ${{ github.event_name == 'issues' && github.event.action == 'edited' }}
      run: |
        MESSAGE="Issue [${{ github.event.issue.number }}](${{ github.event.issue.html_url }}) (_${{ github.event.issue.title }}_) edited"
        python .ci/matrix.py \
        -m "$MESSAGE" \
        -s ${{ secrets.MATRIX_SERVER }} \
        -u ${{ secrets.MATRIX_USER }} \
        -t ${{ secrets.MATRIX_ACCESS }} \
        -r ${{ env.ROOM }}

    - name: Dispatch message - issue milestoned
      if: ${{ github.event_name == 'issues' && github.event.action == 'milestoned' }}
      run: |
        MESSAGE="Issue [${{ github.event.issue.number }}](${{ github.event.issue.html_url }}) (_${{ github.event.issue.title }}_) milestoned for ${{ github.event.issue.milestone.title }}"
        python .ci/matrix.py \
        -m "$MESSAGE" \
        -s ${{ secrets.MATRIX_SERVER }} \
        -u ${{ secrets.MATRIX_USER }} \
        -t ${{ secrets.MATRIX_ACCESS }} \
        -r ${{ env.ROOM }}

    - name: Dispatch message - issue closed
      if: ${{ github.event_name == 'issues' && github.event.action == 'closed' }}
      run: |
        MESSAGE="Issue [${{ github.event.issue.number }}](${{ github.event.issue.html_url }}) (_${{ github.event.issue.title }}_) closed"
        python .ci/matrix.py \
        -m "$MESSAGE" \
        -s ${{ secrets.MATRIX_SERVER }} \
        -u ${{ secrets.MATRIX_USER }} \
        -t ${{ secrets.MATRIX_ACCESS }} \
        -r ${{ env.ROOM }}

    - name: Dispatch message - new PR
      if: ${{ github.event_name == 'pull_request' && github.event.action == 'opened' }}
      run: |
        MESSAGE="New PR [${{ github.event.pull_request.number }}](${{ github.event.pull_request.html_url }}) (_${{ github.event.pull_request.title }}_) created"
        python .ci/matrix.py \
        -m "$MESSAGE" \
        -s ${{ secrets.MATRIX_SERVER }} \
        -u ${{ secrets.MATRIX_USER }} \
        -t ${{ secrets.MATRIX_ACCESS }} \
        -r ${{ env.ROOM }}

    - name: Dispatch message - PR edited
      if: ${{ github.event_name == 'pull_request' && github.event.action == 'edited' }}
      run: |
        MESSAGE="PR [${{ github.event.pull_request.number }}](${{ github.event.pull_request.html_url }}) (_${{ github.event.pull_request.title }}_) edited"
        python .ci/matrix.py \
        -m "$MESSAGE" \
        -s ${{ secrets.MATRIX_SERVER }} \
        -u ${{ secrets.MATRIX_USER }} \
        -t ${{ secrets.MATRIX_ACCESS }} \
        -r ${{ env.ROOM }}

    - name: Dispatch message - PR closed
      if: ${{ github.event_name == 'pull_request' && github.event.action == 'closed' }}
      run: |
        MESSAGE="PR [${{ github.event.pull_request.number }}](${{ github.event.pull_request.html_url }}) (_${{ github.event.pull_request.title }}_) closed"
        python .ci/matrix.py \
        -m "$MESSAGE" \
        -s ${{ secrets.MATRIX_SERVER }} \
        -u ${{ secrets.MATRIX_USER }} \
        -t ${{ secrets.MATRIX_ACCESS }} \
        -r ${{ env.ROOM }}
